name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # Run tests
      - name: Run Tests
        run: pytest tests/

      # Build and push Docker image
      - name: Docker Build and Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t preksha7/ecommerce-churn-api .
          docker tag preksha7/ecommerce-churn-api:latest preksha7/ecommerce-churn-api:latest
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker push preksha7/ecommerce-churn-api:latest
